# Generated by Django 5.0.1 on 2024-01-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='artist/covers'),
        ),
        migrations.AddField(
            model_name='artist',
            name='verfied',
            field=models.BooleanField(default=False),
        ),
    ]
