# Generated by Django 5.0.1 on 2024-01-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_alter_song_playlists'),
        ('user', '0002_artist_cover_artist_verfied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='followed_artists',
            field=models.ManyToManyField(blank=True, null=True, related_name='followed_artists', to='user.artist'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='liked_playlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_playlists', to='song.playlist'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='liked_songs',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_songs', to='song.song'),
        ),
    ]
